### ISSUE TITLE
How do custom cards work?

### ISSUE THREAD

**Issue by bruvv** [basbruss/Minimalist-Dashboards#1]
Thanks for this awesome example! But how is it possible to get the custom-cards working? When I copy your code I get: 
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/3063928/153944963-85c43b70-4e64-4780-9135-86f145bb1a80.png">

**Comment by basbruss** [comment]
All my custom_cards are made for mine HA-setup. They are not part of minimalist  UI. But they can be a found in 1 file: https://github.com/basbruss/Minimalist-Dashboards/blob/main/custom_cards/custom_design.yaml Also directly copying the Lovelace files from this repo can result in problems and is not advised. Because all the entities are user specific and based on my local system. 

If you want to know more about custom cards you could check this page: https://ui-lovelace-minimalist.github.io/UI/setup/custom_cards/

**Comment by bruvv** [comment]
Thanks @basbruss so I did drop them in the right directory. But they're not being picked up. Anything I am doing wrong?

**Comment by basbruss** [comment]
For every change in `config/ui_lovelace_minimalist/` you have to reload the integration. This can be done with hitting "c" on your keyboard and select UI Lovelace minimalist or go to the server page and reload. Than you have to reload your dashboard to apply the changes.

**Comment by bruvv** [comment]
Awesome! I had no idea about the `c` button. Nice catch. Unfortunately it didn't work. I had to restart home assistant for the customs cards to work :) thanks for explaining!
